#!/usr/bin/expect

set repo [lindex $argv 0]
set username [lindex $argv 1]
set password [lindex $argv 2]

spawn git clone "$repo"
if {$argc > 2} {
    expect "Username*:"
    send "$username\r"

    expect "Password*:" {send "$password\r"}
}
interact
